public class CuentaCorreo {
        private String correo;
            private String password;
                private String nombre;
                    private Correo[] bandeja;

                        public CuentaCorreo(String correo, String password, String nombre) {
                                this.correo = correo;
                                        this.password = password;
                                                this.nombre = nombre;
                                                        this.bandeja = new Correo[100];
                                                            }

                                                                public String getCorreo() {
                                                                        return correo;
                                                                            }

                                                                                public String getPassword() {
                                                                                        return password;
                                                                                            }

                                                                                                public String getNombre() {
                                                                                                        return nombre;
                                                                                                            }

                                                                                                                public boolean recibirCorreo(Correo c) {
                                                                                                                        for (int i = 0; i < bandeja.length; i++) {
                                                                                                                                    if (bandeja[i] == null) {
                                                                                                                                                    bandeja[i] = c;
                                                                                                                                                                    return true;
                                                                                                                                                                                }
                                                                                                                                                                                        }
                                                                                                                                                                                                return false;
                                                                                                                                                                                                    }

                                                                                                                                                                                                        public void mostrarBandeja() {
                                                                                                                                                                                                                System.out.println("\nCuenta: " + correo + " | Usuario: " + nombre);

                                                                                                                                                                                                                        int noLeidos = 0;
                                                                                                                                                                                                                                int total = 0;

                                                                                                                                                                                                                                        for (int i = 0; i < bandeja.length; i++) {
                                                                                                                                                                                                                                                    if (bandeja[i] != null) {
                                                                                                                                                                                                                                                                    total++;
                                                                                                                                                                                                                                                                                    String estado = bandeja[i].isVisto() ? "Leído" : "Nuevo";

                                                                                                                                                                                                                                                                                                    if (!bandeja[i].isVisto()) {
                                                                                                                                                                                                                                                                                                                        noLeidos++;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        System.out.println(i + " - " +
                                                                                                                                                                                                                                                                                                                                                                                bandeja[i].getRemitente() + " - " +
                                                                                                                                                                                                                                                                                                                                                                                                        bandeja[i].getTitulo() + " - " +
                                                                                                                                                                                                                                                                                                                                                                                                                                estado);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("\nCorreos sin leer: " + noLeidos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Total: " + total + "\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public void leerCorreo(int pos) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (pos >= 0 && pos < bandeja.length && bandeja[pos] != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bandeja[pos].mostrar();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bandeja[pos].marcarVisto();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Ese correo no existe.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public void limpiarLeidos() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < bandeja.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (bandeja[i] != null && bandeja[i].isVisto()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bandeja[i] = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Se eliminaron los correos leídos.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
}