import java.util.Scanner;

public class SistemaCorreos {
    static CuentaCorreo[] cuentas = new CuentaCorreo[100];
        static CuentaCorreo actual = null;
            static Scanner sc = new Scanner(System.in);

                public static void main(String[] args) {

                        while (true) {
                                    if (actual == null) {
                                                    menuInicio();
                                                                } else {
                                                                                menuPrincipal();
                                                                                            }
                                                                                                    }
                                                                                                        }

                                                                                                            public static void menuInicio() {
                                                                                                                    System.out.println("\n1. Iniciar sesión");
                                                                                                                            System.out.println("2. Crear cuenta");
                                                                                                                                    System.out.print("Opción: ");
                                                                                                                                            int op = sc.nextInt();
                                                                                                                                                    sc.nextLine();

                                                                                                                                                            if (op == 1) {
                                                                                                                                                                        login();
                                                                                                                                                                                } else if (op == 2) {
                                                                                                                                                                                            crearCuenta();
                                                                                                                                                                                                    }
                                                                                                                                                                                                        }

                                                                                                                                                                                                            public static void login() {
                                                                                                                                                                                                                    System.out.print("Correo: ");
                                                                                                                                                                                                                            String correo = sc.nextLine();
                                                                                                                                                                                                                                    System.out.print("Contraseña: ");
                                                                                                                                                                                                                                            String pass = sc.nextLine();

                                                                                                                                                                                                                                                    for (CuentaCorreo c : cuentas) {
                                                                                                                                                                                                                                                                if (c != null && c.getCorreo().equals(correo) && c.getPassword().equals(pass)) {
                                                                                                                                                                                                                                                                                actual = c;
                                                                                                                                                                                                                                                                                                System.out.println("Bienvenido " + c.getNombre());
                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                            System.out.println("Datos incorrectos.");
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    public static void crearCuenta() {
                                                                                                                                                                                                                                                                                                                                                            System.out.print("Nuevo correo: ");
                                                                                                                                                                                                                                                                                                                                                                    String correo = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                            for (CuentaCorreo c : cuentas) {
                                                                                                                                                                                                                                                                                                                                                                                        if (c != null && c.getCorreo().equals(correo)) {
                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Ese correo ya existe.");
                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Nombre: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                            String nombre = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Contraseña: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            String pass = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < cuentas.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (cuentas[i] == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cuentas[i] = new CuentaCorreo(correo, pass, nombre);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actual = cuentas[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Cuenta creada correctamente.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("No hay espacio para más cuentas.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public static void menuPrincipal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("\n1. Ver bandeja");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("2. Enviar correo");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("3. Leer correo");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("4. Limpiar leídos");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("5. Cerrar sesión");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Opción: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int op = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            switch (op) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        actual.mostrarBandeja();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    enviarCorreo();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.print("Posición: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int pos = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actual.leerCorreo(pos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            actual.limpiarLeidos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 5:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        actual = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Sesión cerrada.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static void enviarCorreo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.print("Para: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        String destino = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CuentaCorreo receptor = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (CuentaCorreo c : cuentas) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (c != null && c.getCorreo().equals(destino)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    receptor = c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (receptor == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Ese usuario no existe.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.print("Asunto: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                String asunto = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.print("Mensaje: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                String msg = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Correo nuevo = new Correo(actual.getCorreo(), asunto, msg);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (receptor.recibirCorreo(nuevo)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Correo enviado.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("El inbox del usuario está lleno.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }